# Generated by Django 2.0 on 2018-08-27 08:05

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('worktrend', '0003_worktrendpagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktrendpagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='worktrend.WorktrendPage'),
        ),
    ]
